"""Add ai_generated_summary to Problem model

Revision ID: 1a864bdebf4e
Revises: e087af220187
Create Date: 2025-06-03 12:56:34.926250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a864bdebf4e'
down_revision = 'e087af220187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_generated_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('ai_generated_summary')

    # ### end Alembic commands ###
