"""Add sentiment fields to Problem model

Revision ID: 5f6055e23e08
Revises: 
Create Date: 2025-05-31 21:41:35.039985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6055e23e08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sentiment_label', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('sentiment_label')
        batch_op.drop_column('sentiment_score')

    # ### end Alembic commands ###
