"""Add problem_tags field to Problem model

Revision ID: e087af220187
Revises: 5f6055e23e08
Create Date: 2025-05-31 22:08:24.126287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e087af220187'
down_revision = '5f6055e23e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_tags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('problem_tags')

    # ### end Alembic commands ###
